### ISSUE TITLE
Extract REALM from UPN

### ISSUE THREAD

**Issue by MatthiasLaechele** [sbidy/privacyIDEA-ADFSProvider#24]
In addition to #23 a dynamic realm selection would be nice instead of a fixed value in config.xml
In case of UPN the domain name or in case of SAMAccountName the preceding DOMAIN\...

**Comment by cornelinux** [comment]
Unfortunately the UPN is not always constructed from "sAMAccountName@domain".
The UPN can be "givenname.surname@domain", while the sAMAccountName ist "user43".

But this is fine - we are thinking about a mangle event handler in the privacyIDEA backend... 
https://github.com/privacyidea/privacyidea/issues/1810

**Comment by MatthiasLaechele** [comment]
I'm aware about the different parts. From my point of view a majority is using the primary SMTP address as UPN. Of course, in my setup i would use the UPN also as login name in privacyIDEA

If the login name to adfs is some.body@mycorp.xx, the provider could send these login info's to privacy idea
- username: some.body@mycorp.xx
- realm: mycorp.xx

**Comment by cornelinux** [comment]
I am not precisely aware, what the ADFS plugin actually sends and what the user needs to enter at the Plugin.
However: Within privacyIDEA you can also define multiple Login Attributes in the LDAP resolver. This can ease the part at the backend.
https://privacyidea.readthedocs.io/en/latest/configuration/useridresolvers.html#ldap-resolver

**Comment by sbidy** [comment]
In the 1.3.5 the feature is not implemented. The realm is still manually configured in the config.xml because I've to create some new testcases for that.

In the 1.3.5 some perquisites for this feature are implemented. The provider sends `user = some.body@domain.de (UPN) // user = SomeB (SAMaccountName)` and `realm= domain.de (from config.xml) `

@MatthiasLaechele If you need this feature ASAP, please ping me. Maybe we can test this in the "prod" world.

**Comment by sbidy** [comment]
See #36 - closed
