### ISSUE TITLE
Installer Power Shell not working

### ISSUE THREAD

**Issue by MaxDiOrio** [sbidy/privacyIDEA-ADFSProvider#9]
Getting the following when installing on Server 2012 R2.  You probably want to adjust your README to mention that you need to right click the privacyIDEA-ADFSProvider.dll, go to properties, and select "Unblock" before running the Powershell script.  Otherwise you'll get the error below.

PS C:\Program Files\privacyIDEAProvider\Install> .\Install-ADFSProvider.ps1
                Gac-Util: Exception calling "LoadFile" with "1" argument(s): "An attempt was made to load an assembly fr
om a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. T
his release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is
not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink
/?LinkId=155569 for more information."
Register-AdfsAuthenticationProvider : The external authentication method privacyIDEA-ADFSProvider could not be loaded.
Could not load file or assembly 'privacyIDEA-ADFSProvider, Version=1.2.0.0, Culture=neutral,
PublicKeyToken=b6483f285cb7b6eb' or one of its dependencies. The system cannot find the file specified.
At C:\Program Files\privacyIDEAProvider\Install\Install-ADFSProvider.ps1:35 char:1
+ Register-AdfsAuthenticationProvider -TypeName $typeName -Name "privacyIDEA-ADFSP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-AdfsAuthenticationProvider], AuthenticationMethodLoadExcepti
   on
    + FullyQualifiedErrorId : The external authentication method privacyIDEA-ADFSProvider could not be loaded. Could n
   ot load file or assembly 'privacyIDEA-ADFSProvider, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b6483f285cb7b
  6eb' or one of its dependencies. The system cannot find the file specified.,Microsoft.IdentityServer.Management.Commands.AddExternalAuthProviderCommand

**Comment by sbidy** [comment]
Thanks for the information. I'll update the README.

**Comment by B3DTech** [comment]
Back to having this not install.  Files are unblocked.  This time I'm on Windows 2016 and ADFS 4.  Using the latest release - which is the problem.  The actual release has a version of 1.3.0.0, but the DLL is compiled version 1.3.1.0.  As soon as I changed the version in the installer Powershell, it installed.

```
Register-AdfsAuthenticationProvider : The authentication method privacyIDEA-ADFSProvider could not be loaded. Could not load file or 
assembly 'privacyIDEA-ADFSProvider, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b6483f285cb7b6eb' or one of its dependencies. The 
system cannot find the file specified.
At line:1 char:1
+ Register-AdfsAuthenticationProvider -TypeName $typeName -Name "privac ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Register-AdfsAuthenticationProvider], AuthenticationMethodLoadException
    + FullyQualifiedErrorId : The authentication method privacyIDEA-ADFSProvider could not be loaded. Could not load file or assembly 'priv 
   acyIDEA-ADFSProvider, Version=1.3.0.0, Culture=neutral, PublicKeyToken=b6483f285cb7b6eb' or one of its dependencies. The system cannot   
  find the file specified.,Microsoft.IdentityServer.Management.Commands.AddExternalAuthProviderCommand
```

**Comment by B3DTech** [comment]
Few more comments - still need to add the documentation about unblocking the files.

Also, when installing on Server 2016, you need to relax the Powershell execution policy.  Problem I had was:

If the "Turn on Script Execution" group policy is enabled for the computer or user, the user preference is saved, but it is not effective, and PowerShell displays a message explaining the conflict. You cannot use Set-ExecutionPolicy to override a Group Policy, even if the user preference is more restrictive than the policy.

So you can edit the Local Security Policy or via using GPO first - setting the default policy as required.  Then do a gpupdate /force, close and reopen the Powershell window and then run the command.

One additional note when using an ADFS Farm, the Powershell Execution Policy needs to be relaxed on ALL ADFS servers in the farm.  Otherwise the provider will load on the primary ADFS server, but none of the secondary servers.  As soon as I relaxed the Powershell execution policy on my secondary and restarted the service, it loaded successfully.

So this works perfectly well on Server 2016 and ADFS 4.

**Comment by sbidy** [comment]
@B3DTech thanks for the feedback! I've updated the release with the correct installer ps1!
Regarding the execution policy, I've done this with a "little" workaround to bypass only this script through the policy. You don't have to alter your GPOs for that.

PowerShell.exe -ExecutionPolicy Bypass -File <pathToInstaller>.ps1

I'll update the README with the unblocking and execution policy information.

Thanks !! 
Stephan

**Comment by sbidy** [comment]
No feedback - close
